name: Individual 
on: [push, pull_request]
jobs:
  test-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build debug
        run: dotnet build
      - name: Upload a Build Artifact        
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Archive debug
          path: ${{ runner.workspace }}TestProject3/bin/Debug/
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build release
        run: dotnet build
      - name: Upload a Build Artifact        
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Archive release
          path: ${{ runner.workspace }}TestProject3/bin/Release/

